FROM nvcr.io/nvidia/pytorch:21.11-py3

RUN python3 -m pip install --upgrade pip && \
    pip install transformers==4.20.1 && \
    pip install datasets && \
    pip install sentencepiece && \
    pip install tqdm && \
    pip install scipy && \
    pip install pandas && \
    pip install scikit-learn && \
    pip install nltk && \
    pip install spacy && \
    python3 -m spacy download en_core_web_sm && \
    pip install h5py
